### ISSUE TITLE
Would it be possible to save Highlights?

### ISSUE THREAD

**Issue by danielnehrig** [Pocco81/HighStr.nvim#1]
Title.
on adding highlight maybe adding some entries in a file
and the file is read on plugin load to get a save state of markers

**Comment by kdav5758** [comment]
Yes it's possible, but not at the moment. I was actually discussing it with a guy under my reddit post. For now, I'll go and it to the TO-DO list and leave this issue open...

**Comment by siduck76** [comment]
I need this feature too! I want to make a file having some mappings written in it and then viewing that file in a floating window, so basically a mappings cheatsheet thingy. something like this 
![image](https://user-images.githubusercontent.com/59060246/123509913-ea0b1c80-d695-11eb-9275-a52a5c532af9.png)

it would be great to save the highlights too so I could replicate this cheatsheet thing without using whichkey.nvim

**Comment by siduck76** [comment]
@Pocco81 Let me know when this gets implemented.

**Comment by Pocco81** [comment]
@siduck76 of course, I will. If you want you could also subscribe to the issue.

**Comment by siduck76** [comment]
> @siduck76 of course, I will. If you want you could also subscribe to the issue.

When is this feature gonna be added :(

**Comment by Pocco81** [comment]
Oops! Sorry for taking so long to implement this! Here it is:

https://user-images.githubusercontent.com/58336662/127716570-9c11cbb8-505d-4a23-af8c-fc463f2ee2df.mp4

I'll merge it with main as soon as possible.

**Comment by Pocco81** [comment]
You're welcome :)

**Comment by danielnehrig** [comment]
if i do `HSExport`
following errors occurs

```
...Str.nvim/lua/high-str/tools/tool-exportimport/export.lua:96: bad argument #1 to 'next' (table expected, got string)
stack traceback:
^I[C]: in function 'next'
^I...Str.nvim/lua/high-str/tools/tool-exportimport/export.lua:96: in function 'export'
^I.../site/pack/packer/opt/HighStr.nvim/lua/high-str/main.lua:19: in function <.../site/pack/packer/opt/HighStr.nvim/lua/high-str/main.lua:7> function: builtin#18 ...Str.nvim/lua/high-str/tool
s/tool-exportimport/export.lua:96: bad argument #1 to 'next' (table expected, got string)
stack traceback:
^I[C]: in function 'next'
^I...Str.nvim/lua/high-str/tools/tool-exportimport/export.lua:96: in function 'export'
^I.../site/pack/packer/opt/HighStr.nvim/lua/high-str/main.lua:19: in function <.../site/pack/packer/opt/HighStr.nvim/lua/high-str/main.lua:7> function: builtin#18 ...Str.nvim/lua/high-str/tool
s/tool-exportimport/export.lua:96: bad argument #1 to 'next' (table expected, got string)
stack traceback:
^I[C]: in function 'next'
^I...Str.nvim/lua/high-str/tools/tool-exportimport/export.lua:96: in function 'export'
^I.../site/pack/packer/opt/HighStr.nvim/lua/high-str/main.lua:19: in function <.../site/pack/packer/opt/HighStr.nvim/lua/high-str/main.lua:7>
```

**Comment by Pocco81** [comment]
Github says that I can't play the video because it's corrupt:

![image](https://user-images.githubusercontent.com/58336662/147483062-c1c09709-aed8-49df-be19-0d1c89a3aae5.png)

Could you re-upload it?

**Comment by danielnehrig** [comment]
let me know if this works for you
https://user-images.githubusercontent.com/4050749/147572209-efddb0cc-fe68-405b-8fc3-487be4bce075.mp4

**Comment by danielnehrig** [comment]
https://user-images.githubusercontent.com/4050749/147572306-32a15ffb-339b-4bc3-829a-769418ea3484.mp4

**Comment by danielnehrig** [comment]
looks like was a issue with the encoding which was supported by my browser but probably not yours

**Comment by smsossah** [comment]
Hey @danielnehrig I had this working just fine and then started getting the error you received. It's a bit late so you may have already figured out a way around - I'm using packer so I managed to fix it by manually removing the plugin in the .local/share/nvim/site/pack/packer/start/start/HighStr (Removing/uninstalling via the packer plugin manager didn't work) and deleting my packer_compiled file. Then I attempted to reinstall which worked. But this appears to be a persistent issue..

**Comment by danielnehrig** [comment]
> Hey @danielnehrig I had this working just fine and then started getting the error you received. It's a bit late so you may have already figured out a way around - I'm using packer so I managed to fix it by manually removing the plugin in the .local/share/nvim/site/pack/packer/start/start/HighStr (Removing/uninstalling via the packer plugin manager didn't work) and deleting my packer_compiled file. Then I attempted to reinstall which worked. But this appears to be a persistent issue..

i decided not to care anymore and removed the plugin from my plugin list sorry i couldn't help you
