### ISSUE TITLE
Undefined variable: v:lua

### ISSUE THREAD

**Issue by python-clojure** [Pocco81/HighStr.nvim#4]
Whenever I try to highlight a text, it throws this error
`Undefined variable: v:lua`

Could you please resolve this?

**Comment by Pocco81** [comment]
Sorry but with the information you gave me I can't do much. My best guess would be that you are using an outdated version of NeoVim or a version != nightly or you are just using vim.

Could you:
```lua
call v:lua.print('Hello from Lua!')
```

From command mode and tell me what the output was? Thanks!

**Comment by Pocco81** [comment]
OP never replied. I'll close the issue.
