### ISSUE TITLE
how to auto-enable/disable when entering/exiting visual mode

### ISSUE THREAD

**Issue by hunleyd** [Pocco81/HighStr.nvim#5]
Is there a way to set up an autocmd (or something) to call HSHighlight when entering visual mode and then call HSRmHighlight when exiting visual mode? I have them mapped to F3/F4 as shown in the README but having 'the system' do it automatically would be even better.

**Comment by Pocco81** [comment]
Hey! what exactly do you need? Calling HSHighlight as soon as you enter visual mode will only highlight the current character/thing you are over at the moment and calling HSRmHighlight will remove the highlights from the current line. That doesn't make sense.

Perhaps you meant to run HSHighlight **after** exiting visual mode? That's how the highlighter works in normal document editors.

**Comment by Pocco81** [comment]
Nope, after searching for a while it concluded that it's not possible to do this:

+ [There are no events for leaving or entering visual modes](https://tech.saigonist.com/b/code/list-all-vim-script-events.html)
+ [There was a patch on vim to allow this but it doesn't seem to be available on NeoVim](https://github.com/vim/vim/releases/tag/v8.1.2044)
+ [It is kind of possible to execute commands when entering visual mode, but simply adds another action to the `v` key for entering visual mode](https://stackoverflow.com/questions/15561132/run-command-when-vim-enters-visual-mode)

I'd suggest you simply use a more "simple" mapping, like pressing `h` to highlight visual selection:
```
vnoremap <silent> h :<c-u>HSHighlight 1<CR>
```
