### ISSUE TITLE
Cannot export the higlighting 

### ISSUE THREAD

**Issue by Belamat** [Pocco81/HighStr.nvim#8]
Hi, great plugin : )

in my case i cannot save the highlightings

I highlight something and then :HSExport path/

but it outputs E488: Trailing characters

I've tried with ~/path/path/ 
also creating the folder.

Probably doing something wrong on my side.

**Comment by Pocco81** [comment]
Heya! could you tell me which OS are you using? and also, could you share your config here?

**Comment by Belamat** [comment]
Hi, yes sure.

Im using Debian Gnu/Linux Os

------------------------------------------------------------
SETTINGS:

local set = vim.opt
set.expandtab = true
set.smarttab = true
set.shiftwidth = 1
set.tabstop = 1 
set.mouse = 'a'
set.hlsearch = true
set.incsearch = true
set.ignorecase = true
set.smartcase = true
set.swapfile = false

set.splitbelow = true
set.splitright = true
set.wrap = false
set.scrolloff = 5
set.fileencoding = 'utf-8'
set.termguicolors = true

set.relativenumber = true
set.cursorline = true


set.hidden = true
vim.wo.number = true


-------------------------------------------------------------
TREESITTER
```
return require'packer'.startup(function()
 use 'wbthomason/packer.nvim'
 
 use "lukas-reineke/indent-blankline.nvim"
 
 use 'EdenEast/nightfox.nvim'
 
 use {
  'goolord/alpha-nvim',
  requires = { 'kyazdani42/nvim-web-devicons' },
  config = function ()
  require'alpha'.setup(require'alpha.themes.startify'.config)
  end
 }
 
 use {
  'nvim-treesitter/nvim-treesitter',
  run = ':TSUpdate'
}
 
 use 'nvim-lua/plenary.nvim'
 
 use {
  'nvim-telescope/telescope.nvim',
  requires = { {'nvim-lua/plenary.nvim'} }
 }
 
 use 'sudar/vim-arduino-syntax' 

use "Pocco81/HighStr.nvim"
 
 use {
  'kyazdani42/nvim-tree.lua',
  requires = {
   'kyazdani42/nvim-web-devicons', -- optional, for file icon
   `},`
  config = function() require'nvim-tree'.setup {} end
}


end)
```
------------------------------------------------------------------------------

PACKER CONFIG

return require'packer'.startup(function()
 use 'wbthomason/packer.nvim'
 
 use "lukas-reineke/indent-blankline.nvim"
 
 use 'EdenEast/nightfox.nvim'
 
 use {
  'goolord/alpha-nvim',
  requires = { 'kyazdani42/nvim-web-devicons' },
  config = function ()
  require'alpha'.setup(require'alpha.themes.startify'.config)
  end
 }
 
 use {
  'nvim-treesitter/nvim-treesitter',
  run = ':TSUpdate'
}
 
 use 'nvim-lua/plenary.nvim'
 
 use {
  'nvim-telescope/telescope.nvim',
  requires = { {'nvim-lua/plenary.nvim'} }
 }
 
 use 'sudar/vim-arduino-syntax' 

use "Pocco81/HighStr.nvim"
 
 use {
  'kyazdani42/nvim-tree.lua',
  requires = {
   'kyazdani42/nvim-web-devicons', -- optional, for file icon
   },
  config = function() require'nvim-tree'.setup {} end
}


end)

Using NIGHTFOX COLORSCHEME PLUGIN

**Comment by Belamat** [comment]
``

**Comment by Belamat** [comment]
sorry, it looks like i've closed the issue (and I didnt wanted to do that) I've pasted my config in the prev message

**Comment by Belamat** [comment]
> Heya! could you tell me which OS are you using? and also, could you share your config here?
> 
> Edit: I just saw you ran `:HSExport <path>`, that command shouldn't receive any parameters and the path to which the highlights are exported is actually stored in your config. So starting from there, try running the command alone.



I get it to work !!!

I  was missing the config folder for the pluggin. Ive created it and it worked grear!!

Thanks for the help and for the great plugging!!

Have a nice day !!
